### ISSUE TITLE
Add 'status' field and "archive" smart-actions to every model.

### ISSUE THREAD

**Issue by louisremi** [chez-nestor/backoffice#12]
The aim is to provide both a 'draft' status, and an 'archived' status (because deleted instances cannot be restored).
  - \+ find a way to disable "delete" action on all models
  - \+ add afterFind hooks to all models that filter out instances with status != 1 **unless** the query is explicitely looking for items with a specific status
  - \+ add unit tests to make sure that draft/archived instances are not counted in `Order#getCalculatedProps`

**Comment by vquesnel** [comment]
add scope to each model with a paranoid option to handle a trash

**Comment by vquesnel** [comment]
add segment to each model in oder to retreive datas which were move to trash or draft
