### ISSUE TITLE
It shouldn't be possible to dissociate an order from its client

### ISSUE THREAD

**Issue by louisremi** [chez-nestor/backoffice#229]
In Forest, on the detail view of a Client, it's possible to view all associated Orders, and then it's possible to select orders and use the action "remove".
This action shouldn't be possible!
We need to find a way to detect when it is used, and, instead of removing the OrderId, we need to keep it, but mark the order as deleted.
Also, this action and the delete action shouldn't be possible on an order that has already been (partially) paid.

**Comment by vquesnel** [comment]
Error when we overwrite the Order delete route 
`Unhandled rejection Error: Can't set headers after they are sent.`
