### ISSUE TITLE
Implement automatic late-fees

### ISSUE THREAD

**Issue by louisremi** [chez-nestor/backoffice#52]
## General idea
Late fees should be calculated every day and added to a draft order that will then be used as next-month's rent order.

## Spec:
- Implement instance method `Order#calculateLateFees`: returns late fees for rent that have a due date in the past and that have a negative balance.
- Implement instance method `Client#applyLateFees`: find all pending rent orders of a client, calculate their late fees using the previous method, create or update a draft order with a LateFees OrderItem
- Test those methods

**Comment by vquesnel** [comment]
done 
[https://github.com/chez-nestor/backoffice/tree/automatic_lateFees](url)
