### ISSUE TITLE
[Forest] Add a "duplicate" built-in action

### ISSUE THREAD

**Issue by louisremi** [chez-nestor/backoffice#69]
It would be very cool if it was possible to duplicate an existing recording by selecting it in the list view, then hitting "duplicate" in the action menu, and have the creation view opened with the data of the existing record pre-filled.
Users could then modify a few fields (if needed), then hit "create" and… voilà!

**Comment by arnaudbesnier** [comment]
This is the second time, I hear someone asking for this feature. Waiting for a 3rd user to start thinking about implementing it 😄
