### ISSUE TITLE
Add a "Discount Invoice" smart-action for Order

### ISSUE THREAD

**Issue by louisremi** [chez-nestor/backoffice#94]
When the invoice for an order has been generated, the order cannot be modified or deleted. Modifying or cancelling the Invoice can only be done by creating a new Order with credit Items.
We should provide smart-actions to make this process simpler.

**Comment by vquesnel** [comment]
Cancel Invoice smart action is done

**Comment by louisremi** [comment]
We need to determine the use-cases for this action before starting implementing this action
